### ISSUE TITLE
Linear GD00Z-4 garage opener

### ISSUE THREAD

**Issue by tjshin** [pavoni/pyvera#100]
Hello,

I have a Linear GD00Z-4 garage opener paired with Vera. However, it is not showing in my Home Assistant. When I browse http://vera_ip:3480/data_request?id=lu_sdata I can see the garage opener as one of devices. What I am missing? Any help will be much appreciated.

**Comment by alanfischer** [comment]
Could you post what you see at that url?

**Comment by pavoni** [comment]
On the road - but I while this was added to pyvera - I don’t know if the
contributer (sorry can’t check the name  at the moment) released the HA
binding to make use of the changes.

**Comment by alanfischer** [comment]
Looks like the commit was merged in and should be in the next release of HA:
https://github.com/home-assistant/home-assistant/pull/17419/commits/2c9a4236b0d155a39e545240fdfce8b047467b3a
