### ISSUE TITLE
The "complex" variable functions do not consider service Id

### ISSUE THREAD

**Issue by toggledbits** [pavoni/pyvera#107]
Ref this discussion: https://github.com/home-assistant/home-assistant/issues/18491#issuecomment-479131438

The "complex" functions in pyvera currently look up the variable name in the "states" substructure and operate on the first matching name. However, variable names are not unique in Vera. A state variable is uniquely identified only by the *combination of service Id and variable name*.

I recommend, in addition to providing forms of these functions with an additional `serviceId` argument, that the existing functions be extended to accept "service/variable" syntax for the name, and use the serviceId provided when given (i.e. make sure the selected state variable data matches both service Id and variable name).

The name-only usage should be deprecated. This means all pyvera "convenience" functions like `is_tripped()` and `get_battery_level()` should be amended to include the specific serviceId for the variable retrieved in their implementations. This should be the required practice for all such usage within pyvera, to remove ambiguity.

**Comment by pavoni** [comment]
The vera code initially assumed all the names were unique!

I've generally been trying to avoid the "get complex" functions because they require a poll  - rather than the subscription based functions. I really only left "get_complex" as a fallback for compatibility.

I don't have a thermostat - so am rather cautions about changing this code - @alanfischer did most of the work on this.

**Comment by toggledbits** [comment]
I get it, and unfortunately, he may have unwittingly started off on the wrong foot. No disrespect intended at all, there--his work is great, as is yours after, and it has carried this project far. But almost every integration I've seen with Vera (including my own early efforts) goes with the approach of using `lu_sdata` requests and relying on the relatively quick, simple, lightweight replies one gets back. Unfortunately, time has proven that that is fraught with peril. I can name more integrations that have gone wrong than are right, and issues like thermostats are exactly why--most of them run headlong into exactly this same issue. That's not Greg's fault; Vera also made some bad implementation choices, and here we are. But it's fixable.

I feel strongly that it is possible to correct the missed assumptions without breaking clients like HA that are tied to the current model, at least in the short term. If we give them time to evolve, and tell them how they need to evolve, in the long run those clients will be fine. I would never suggest "fixing" everything and pulling the rug out from underneath them in the process. For now, I really think we can just do a little overloading of existing interfaces, and provide some entirely new interfaces that implement the more complete/correct model, and carry forward without driving existing code into the ditch.

And I'm willing to back up my position with effort, if you're willing to take it that direction.

**Comment by pavoni** [comment]
@toggledbits I have less time to work on HA related stuff than I did - so I wouldn't be able to commit the time to do this myself. As I think you realise it is pretty much a ground up rewrite. From experience the first time round in getting the subscription mechanism to work reliably - a lot of the work will be testing, dealing with timing and race conditions, and odd undocumented behavior!

My enthusiasm is also tempered by the fact that vera switches and sensors are supported pretty well by the current implementation (and my home set up depends on a fast response to switch activations).

However certainly understand there are some issues that are difficult to fix in the current structure, so would certainly be supportive if you want to develop this new approach and supersede the approach here. (I wrote fork initially - although on reflection you might not want to start with a fork!). I'd also be happy to help test etc.

**Comment by alanfischer** [comment]
I also do not foresee myself having time to do any pyvera work in the near future.  However I would be happy to test out any modifications if that is helpful.

**Comment by GaryOkie** [comment]
> And I'm willing to back up my position with effort, if you're willing to take it that direction.

@toggledbits,

I waited a month to ask this, but have you decided to take on the effort to improve pyvera?

I'm a long-time Vera hub user and have greatly appreciated the excellent work your alter-ego Rigpapa has done developing plugins.   I now primarily use the Vera for Zwave and security panel connectivity and leave the rest to HASS.

I am now needing to replace a Wink hub for my elderly parents (also managed by HASS and experiencing yet another extended cloud outage).   I would prefer to get them a VeraPlus but the serious confusion with incorrectly reporting thermostat target set points and not knowing if this will ever be fixed is keeping me away from Vera at this time.

I too would be very happy to assist with testing any pyvera updates!

**Comment by toggledbits** [comment]
Sorry for the slow reply. This one took some soul-searching.

Indeed, because Hass is apparently the major consumer of pyvera, it takes much more than a modification of pyvera to make thermostats and other devices work fully and correctly in Hass, with all of their state available and intact, and properly displayed. The Vera component would also require significant surgery. Combine this with @pavoni 's current satisfaction with the package, and the investment I would face in contributing additionally to the Vera component (assuming those maintainers were even interested) and getting all of these rather serious changes through and blessed by the Hass overlords, I don't see the investment as a good use of my time. At one time, Vera's future was uncertain and Hass looked like a safe alternative, but having been through several frustrating versions of Hass, and with the game changing significantly at Vera following their acquisition and new hardware and rewritten firmware coming, I am resolved to be one of, if not the most, positive influencers in and contributors to the Vera community, and that is where I feel my energies are best used.

**Comment by GaryOkie** [comment]
Thanks Patrick for the thoughtful reply.   I follow the Vera Community rather closely and know full well of your many contributions to this platform and of the work by EZLo to rehabilitate support and development.   Vera's future is indeed much brighter.

I personally view the VeraPlus as one of the best  Z-wave hubs available, and hope it can continue to be a viable dedicated hub to be used in conjunction with Home Assistant going forward.    I thought you were also a Home Assistant as-a-front-end advocate, but I certainly understand why you would prefer to focus on Vera development if your integration with HA has ended.

Now all I can hope for is that the developers who have experience with python-Vera and the HA component renew their interest in fixing the significant issues with the code base.

**Comment by pavoni** [comment]
Closing for now,
