### ISSUE TITLE
variableset request--set the value of a state variable

### ISSUE THREAD

**Issue by toggledbits** [pavoni/pyvera#109]
It does not appear that there is a `variableset` request in current pyvera, so there seems to be no way to set the value of a state variable with it.

There is `set_service_value()`, but I feel this is misnamed. What this function actually does is execute a UPnP action, as long as its name begins with "Set", which not all do and that's a separate issue I mentioned in issue #108. It looks like there is a bit of a disconnect between what actions like "SetTarget" really do, and the ability to set values in state variables. The former and latter may *appear* on the surface to do the same thing, but they are notably different to Vera.

How, for example, might one set the `CurrentLevel` variable in service `urn:micasaverde-com:serviceId:GenericSensor1` to 123? There seems to be no way... but one can do it easily:

    http://ip_address:3480/data_request?id=variableset&DeviceNum=nnn&serviceId=urn:micasaverde-com:serviceId:GenericSensor1&Variable=CurrentLevel&Value=123

There should be a `set_complex_value( device, serviceId, variable, value )` that does this. And IMO, `set_service_value()` should be deprecated--if issue #108 is addressed, `call_service()` could/should then be used instead.

**Comment by pavoni** [comment]
Closing as stale.
