### ISSUE TITLE
pyvera not updating HA; device_list is always empty

### ISSUE THREAD

**Issue by MarkJenniskens** [pavoni/pyvera#114]
The device_list on line 98 of subscribe.py is always empty, thus received changes/data never translates in an event for HA.

(hass.io v0.97.2)

@pavoni Found a fix: #115

**Comment by guerrerotook** [comment]
Hi @MarkJenniskens I found the same in my HA installation and I ran the examples/device/listener.py from this repo and I confirm is not working. At the same time I confirm what you said about the line 98 of the subscripbe.py. 

What I did on my code and now is working is convert device_id from string to in like this:

`device_list = self._devices.get(int(device_id), ())`

And now the notifications from Vera are working again. I'm going to try to do a pull request to the repo!

**Comment by MarkJenniskens** [comment]
I did a PR for that: #115
But there may be differences between Vera versions. Hopefully @pavoni can shed some light on it or merge the PR.

**Comment by guerrerotook** [comment]
I didn't see that! I fix my installation manually and it's working now.

**Comment by pavoni** [comment]
I'll merge and release these - sounds like it certainly won't make anything worse, although it's possible there are other related issues.

I guess there is a revised vera firmware than changes the types.

Can you guys list what firmware versions you're using? I generally don't update my firmware after previous updates broken things (with zwave rather than pyvera!).

**Comment by guerrerotook** [comment]
My Vera controller is using 1.7.4452 version and HA is 0.97.2

**Comment by pavoni** [comment]
So I guess that's the latest firmware. I'm still on 1.7.4000.

**Comment by pavoni** [comment]
I've released this as 0.3.4, can you guys check it works OK on your firmware? I'll check on mine.

**Comment by MarkJenniskens** [comment]
> I've released this as 0.3.4, can you guys check it works OK on your firmware? I'll check on mine.

Great, will check!
Firmware:  1.7.1040 (latest for my old Vera Lite)

**Comment by GaryOkie** [comment]
FYI, the latest Vera UI7 version (released April 2019) is 7.029.  The latest firmware that came out the same time is **1.7.4452 Vera Edge / 1.7.4453 Vera Plus / 1.7.4454 Vera Secure**.    I understand that Vera's older than these 3 models will no longer be updated.   Officially noted [here](https://community.getvera.com/t/ui7-web-ui-7-0-29-ga-april-24-2019/208088).

I'm running the latest HASSIO 97.2 and of course, it's severely crippled.   It even messed up the HA/Google Assistant associations to the zwave devices managed by Vera.

What can I do to install this 3.4 update on HASSIO?  I can test that it work OK on the latest VeraPlus firmware.   Or must I wait for 97.x once the PR is merged?

**Comment by MarkJenniskens** [comment]
> FYI, the latest Vera UI7 version (released April 2019) is 7.029. The latest firmware that came out the same time is **1.7.4452 Vera Edge / 1.7.4453 Vera Plus / 1.7.4454 Vera Secure**. I understand that Vera's older than these 3 models will no longer be updated. Officially noted [here](https://community.getvera.com/t/ui7-web-ui-7-0-29-ga-april-24-2019/208088).
> 
> I'm running the latest HASSIO 97.2 and of course, it's severely crippled. It even messed up the HA/Google Assistant associations to the zwave devices managed by Vera.
> 
> What can I do to install this 3.4 update on HASSIO? I can test that it work OK on the latest VeraPlus firmware. Or must I wait for 97.x once the PR is merged?

If you can't wait for an HA update which includes pyvera 0.3.4 you can do the following **at your own risk;**

- SSH into you're hass.io

- Enter the HA docker:  `docker exec -it homeassistant /bin/bash`

- Edit the manifest of the Vera component and set the version to 0.3.4: `vi /usr/src/homeassistant/homeassistant/components/vera/manifest.json`

- then `pip install pyvera==0.3.4`

- `exit`

- `hassio ha restart`

**Comment by GaryOkie** [comment]
Thanks very much for the Hassio pyvera update instructions!   I can easily manage that once I get back home in a couple of days.  Maybe by then, the official update will be ready as well.

**Comment by smurry** [comment]
@MarkJenniskens , thanks!  I was able to follow your instructions for updating PyVera and it appears that it may have solved the issue for me.  Vera states are again showing up.  In the past, sometimes states have stopped updating in HA after a period of time.  I will monitor and post if they stop updating again.

**Comment by mdrileynyc** [comment]
Had the same problem. Above workaround to install 0.3.4 fixed things.
HA 0.97.2
Vera3 1.7.1040  (no more updates for vera3)

**Comment by MYeager1967** [comment]
While this is a great fix, the files aren't in the same place for those of us running HA (non HASSIO) in a Docker container. I'm running it on a Synology NAS in Docker and although I found a Vera folder under components, there's no manifest.json in it...

**Comment by MarkJenniskens** [comment]
That's wierd, I thought they used the same source.
Can you post the exact folder location?

**Comment by MYeager1967** [comment]
I've got a few busy days ahead, but I'll get to it as soon as possible.

**Comment by keithmichael** [comment]
I am running HA in virtualenv and my path is :
`/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/vera/manifest.json`

The modification works for me! Thank you everyone. 

FYI - We should heed @MarkJenniskens warning - I believe we will need to keep updating this manifest.json file each time HA releases a new update, until HA includes .34, otherwise...cats and dogs.

**Comment by MYeager1967** [comment]
Mine is in /usr/src/app/homeassistant/components/vera and I found the manifest.json file. Took a bit of effort to modify it, but it's done. Now to see if it works... Would it be easier to drop a copy of the component in the custom components directory until it's fixed? Not sure how to do that, but it's a thought...

**Comment by markiper** [comment]
Just made the modification as per @MarkJenniskens instructions, and all is working (HA 0.97.2 / vera 1.7.4453) .

**Comment by GaryOkie** [comment]
> ... I believe we will need to keep updating this manifest.json file each time HA releases a new update, until HA includes .34, otherwise...cats and dogs.

FYI  - The HA .98 release notes confirm pyvera 3.4 is included.   

- Update pyvera to 0.3.4 (@KptnKMan - #25986) (vera docs)
- cats and dogs at peace!

**Comment by pavoni** [comment]
Based on the comments above, I'll close this. Please re-open is the issues re-occur.
