### ISSUE TITLE
Vera 7.31 breaks thermostat?

### ISSUE THREAD

**Issue by brantlk** [pavoni/pyvera#129]
Updated Vera firmware today (currently reports `1.7.4955 (7.31)`) and since then the thermostat isn't working (in Home Assistant).

Here's what pyvera is currently showing for the device:

 ```
>>> thermostat = controller.get_device_by_id(175)
>>> thermostat.category
0
````

Not sure if there's anything that pyvera can do about this, looks like the vera is reporting category 0 for some reason.

**Comment by brantlk** [comment]
Here's the output for `id=sdata`:

```
        {
            "altid": "58",
            "batterylevel": "100",
            "category": 0,
            "commFailure": "0",
            "comment": "",
            "configured": "1",
            "cool": "68.00",
            "fanmode": "Auto",
            "heat": "68.00",
            "hvacstate": "Idle",
            "id": 175,
            "mode": "HeatOn",
            "name": "Thermostat",
            "parent": 1,
            "room": 10,
            "setpoint": "68.00",
            "state": -1,
            "subcategory": 1,
            "temperature": "68.00"
        },
```

Category says 0 for some reason.

**Comment by brantlk** [comment]
I reported this to vera support since it seems the device isn't working as expected.

**Comment by brantlk** [comment]
unplugged the vera and plugged it back in and now the vera reports the correct info and things are working again.

**Comment by pavoni** [comment]
Great news - thanks.
How is the firmware update working for you?

**Comment by brantlk** [comment]
I haven't noticed any differences after the update. Was hoping that they'd add support for the aeotech doorbell 6... just checked the vera site and they say that it's supported now so I need to try it out.
