### ISSUE TITLE
pyvera install

### ISSUE THREAD

**Issue by orginda** [pavoni/pyvera#143]
hi, i'm trying to integrate veraplus with hassio, i'm reading all the posts i find but i can't find or better it is surely the fault of my inexperience but i can't solve the integration of veraplus with hassio, i added the integration of vera in the devices , I see them on hassio but it does not update the status, I understand that biogna update pyvera with the latest version and I launched the command pip install pyvera == 0.3.11 from the terminal but still I do not see anything happening, it is possible to have a basic explanation of the procedure, I don't know what to do.

**Comment by pavoni** [comment]
It's normally straight forward, you should just need to add your vera controller path (mine is `http://192.168.1.162:3480/`) and then the rest should be pretty automatic.

If you add the following lines to your home assistant `configuration.yaml`, you should get more useful information in the home assistant log:

```
logger:
  default: warning
  logs:
    homeassistant.components.vera: debug
    pyvera: debug
```

Let me know if you see anything useful in the log.

Vera runs a dedicated thread to get updates - so it may be something is preventing that running. The logs should tell us.

Can you control devices from HA (even if the state doesn't come back correctly)?

**Comment by orginda** [comment]
yes I can check them but without having the status updates regarding pir sensors and door sensors, but on the interface of vera I see all the changes, I also added those lines on configuration.jaml

**Comment by pavoni** [comment]
With debug turned on you should see traces like these:
```
2021-01-25 15:47:32 DEBUG (SyncWorker_4) [pyvera] Polling for Vera changes
2021-01-25 15:47:32 DEBUG (SyncWorker_4) [pyvera] get_changed_devices() requesting payload {'timeout': 30, 'minimumdelay': 200, 'id': 'lu_sdata', 'dataversion': 1, 'loadtime': 0}
2021-01-25 15:47:32 DEBUG (SyncWorker_4) [pyvera] get_alerts() requesting payload {'LoadTime': 0, 'DataVersion': 1, 'id': 'status'}
2021-01-25 15:47:32 DEBUG (SyncWorker_4) [pyvera] Poll returned
2021-01-25 15:47:32 DEBUG (SyncWorker_4) [pyvera] Event: Study uplighters, state -1, alerts 0, {"name": "Study uplighters", "altid": "2", "id": 3, "category": 2, "subcategory": 0, "room": 4, "parent": 1, "configured": "1", "commFailure": "0", "kwh": "20.5500", "status": "0", "watts": "0.0", "level": "0", "state": -1, "comment": ""}
2021-01-25 15:47:32 DEBUG (SyncWorker_4) [pyvera] Event: Bookcase Uplighters, state -1, alerts 0, {"name": "Bookcase Uplighters", "altid": "4", "id": 15, "category": 3, "subcategory": 0, "room": 1, "parent": 1, "configured": "1", "commFailure": "0", "status": "0", "state": -1, "comment": ""}
```

**Comment by orginda** [comment]
where do i see this screen? in system log I don't see these entries

**Comment by pavoni** [comment]
It's in Configuration / Logs

**Comment by orginda** [comment]
![log hassio](https://user-images.githubusercontent.com/65851478/105742930-63161480-5f3c-11eb-9c70-f7ad83c8385d.jpg)

the only logs is in supervisor, I guess I'm not understanding, can you be more precise? I'm sorry

**Comment by pavoni** [comment]
![Screenshot 2021-01-25 at 17 41 12](https://user-images.githubusercontent.com/4487313/105744166-a1a7d100-5f34-11eb-8cb0-e2128da5a2b3.png)

**Comment by orginda** [comment]
![Uploading log hassio.jpg…]()

**Comment by orginda** [comment]
![log hassio](https://user-images.githubusercontent.com/65851478/105746233-79719f80-5f3f-11eb-85c7-a3ec8d8988a1.jpg)

**Comment by pavoni** [comment]
So that's not able to connect to your vera controller at all. 

My guess is you have the wrong IP address, or some sort of network problem.

**Comment by orginda** [comment]
the ip address is found, heart attack I can activate hassio checks and check its activation status on the veraplus page

**Comment by pavoni** [comment]
I'm not sure what you mean - but while you see that type of error in the home assistant log  pyvera isn't connecting to your vera controller - so there is nothing more I can do to help.

**Comment by orginda** [comment]
from hassio I can activate the veraplus devices, but I can't see the status of the sensors

**Comment by pavoni** [comment]
With that error I don't believe you have any connection to Vera devices at all from hassio. So I don't know what you've got activated - but I don't think it's vera devices!

**Comment by orginda** [comment]
![log hassio](https://user-images.githubusercontent.com/65851478/105749432-b049b480-5f43-11eb-96f6-4f5492ebcd56.jpg)

in any case I did a restart and the error in the log is not there now but the situation has remained the same

**Comment by pavoni** [comment]
If you click on the button at the bottom - it should show you the full log.

**Comment by orginda** [comment]
![log hassio](https://user-images.githubusercontent.com/65851478/105753542-2ef52080-5f49-11eb-8e01-59c8c4e20d57.jpg)

**Comment by pavoni** [comment]
That looks good. 

So now you need to watch the log and do some detective work. Change a switch or sensor and see what happens in the log.

**Comment by orginda** [comment]
just restarted it seemed that the messages in the log were created but now everything has stopped

**Comment by pavoni** [comment]
I think you’re going to need to get a bit more on top of Home Assistant before I can help.

This is really a place for raising technical issues with the pyvera python library, not broader home assistant help.

**Comment by orginda** [comment]
sorry if I wasted your time, I try and try again to read the log but the updates are not recorded except in the first moments that I restart hassio and after all is silent, in any case thanks for the help, I admit my incompetence on the subject.

**Comment by pavoni** [comment]
No problem.

Once you’ve got on top of home assistant, reading the logs etc, feel free to come back if you still have a problem with Vera devices not updating.

**Comment by orginda** [comment]
the problems are always there, but I try to investigate the problem well so as not to disturb you, trying to understand even if it has to do the installation on proxmox, I will do all the necessary investigations and as a last hypothesis I return to ask questions and if I have need, thanks again
