### ISSUE TITLE
Return power useage attribute

### ISSUE THREAD

**Issue by pavoni** [pavoni/pyvera#17]
Requested by @snizzleorg for HomeAssistant.

**Comment by snizzleorg** [comment]
Thanks.

This was my work-around but apparently lead to an unresponsive vera:

```
 - platform: rest
   resource: 'http://192.168.178.187:3480/data_requestid=variableget&DeviceNum=60&serviceId=urn:micasaverde-com:serviceId:EnergyMetering1&Variable=Watts'
   method: get
   name: "hall_lamp_watts"
   unit_of_measurement: "W"
   value_template: '{{ value|round(1) }}'
```

**Comment by pavoni** [comment]
Have coded both the Vera and HA parts - so will test both over the next couple of days

https://github.com/pavoni/pyvera/pull/19

**Comment by pavoni** [comment]
Now in the dev branch of HA

**Comment by snizzleorg** [comment]
I think there is a little problem in this. The power usage should be reported in W or mW (not in mWh) as this would be the energy consumed...

In any case the It's working just the unit is wrong

**Comment by pavoni** [comment]
@snizzleorg This isn't a pyvera issue - but a home assistant issue (with the base switch code rather tha the vera switch code)

I meant to raise an issue when  I coded it. I'll do that and tag you.
