### ISSUE TITLE
VeraLite dimmers and locks

### ISSUE THREAD

**Issue by amccardie** [pavoni/pyvera#24]
For whatever reason, my VeraLite (UI 5, fw 1.5.672) returns different category names for dimmers and door locks than pyvera expects.

Specifically, instead of "Dimmable Switch", VeraLite returns "Dimmable Light" and instead of "Doorlock" it returns "Door lock".

Home Assistant can't find either my dimmers or my lock unless I change the strings in both pyvera/__init__.py  and homeassistant/components/vera.py. 

Let me know if you need more information or if I can help out.

**Comment by pavoni** [comment]
You could upgrade your Vera. I know there were issues - but mine works pretty well on the latest UI-7.

However if you don't want to upgrade, happy to add another set of device strings. Is it just dimmers and locks that don't work?

Either put together a PR if you're a tech guy, or make a list comparing the ones we use in the code - and I'll put something together.

On vacation this week - so likely to take a couple of weeks.

**Comment by amccardie** [comment]
In my case, yes, it's just dimmers and locks. I've been avoiding UI7 mainly because UI5 has been very stable for me. If upgrading to UI7 will fix my issue though, I may take the plunge.

I can patch the files pretty quickly when HA is updated, so there's no urgency at all. Also, if I get a chance, I'll try to set up a pull request. I haven't worked with GitHub (or git) before, so it will be an adventure.

**Comment by pavoni** [comment]
Included in https://github.com/pavoni/pyvera/pull/27 and also in the dev branch of HA.
