### ISSUE TITLE
Cover position not updated correctly

### ISSUE THREAD

**Issue by arjenfvellinga** [pavoni/pyvera#44]
Again not sure if this is a pyvera or Hass issue.

But in Hass, if I open my curtain for 50% and then call (full) open (or close) the interface still shows position 50% afterwards. And a side effect is that the controls (arrow up and down) are both enabled, but one should be greyed out.

**Comment by pavoni** [comment]
It's important the position is correct, because if it isn't - then HA will enable / disable the buttons incorrectly.

Will double check my cover at the weekend - but I'm pretty sure mine works (I use a Fibaro FGR-222). What blind controller are you using?

The vera commands for `position` and `open/close/stop` are different. However (if I remember correctly) my controller sends position updates in response to the `open/close/stop` commands, so I don't default the state in the code after you click open/close.

It's quite possible your controller doesn't send position updates, so needs me to default them. The only tricky part of this is what happens when you click `stop`!

Can you turn up the logging level to `debug` in pyvera? (https://home-assistant.io/components/logger/). This should trace the commands sent - and the status updated that come back. This should give us more clues about what is happening.

**Comment by arjenfvellinga** [comment]
I have a complete system from http://www.forestgroup.com This is their documentation on the zwave part: http://www.forestgroup.com/products/pdf/Shuttle_S_L_Z_Wave_EN.pdf

With the following logging

```
logger:
  default: error
  logs:
    pyvera: debug
    homeassistant.components: debug
```

I get for setting the curtains to 51 percent and afterwards to closed:
```
17-03-21 17:41:12 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 1823110032: Received {'service_data': {'position': 51, 'entity_id': 'cover.gordijnen_21'}, 'service': 'set_cover_position', 'domain': 'cover', 'type': 'call_service', 'id': 10}
17-03-21 17:41:12 DEBUG (Thread-6) [pyvera] Result of vera_request with payload {'newLoadlevelTarget': 51, 'serviceId': 'urn:upnp-org:serviceId:Dimming1', 'action': 'SetLoadLevelTarget', 'id': 'lu_action'}: { "u:SetLoadLevelTargetResponse": { "JobID": "62447" } }
17-03-21 17:41:12 INFO (Vera Poll Thread) [pyvera.subscribe] Poll returned
17-03-21 17:41:12 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 1823110032: Sending {'success': True, 'type': 'result', 'id': 10, 'result': None}
17-03-21 17:41:13 INFO (Vera Poll Thread) [pyvera.subscribe] Poll returned
17-03-21 17:41:13 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 1823110032: Sending {'event': {'event_type': 'state_changed', 'time_fired': datetime.datetime(2017, 3, 21, 17, 41, 13, 571784, tzinfo=<UTC>), 'origin': 'LOCAL', 'data': {'entity_id': 'cover.gordijnen_21', 'old_state': <state cover.gordijnen_21=open; Vera Device Id=21, current_position=100, supported_features=15, friendly_name=Gordijnen @ 2017-03-21T18:40:12.235209+01:00>, 'new_state': <state cover.gordijnen_21=open; Vera Device Id=21, current_position=51, supported_features=15, friendly_name=Gordijnen @ 2017-03-21T18:40:12.235209+01:00>}}, 'type': 'event', 'id': 2}
17-03-21 17:41:13 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 1826402992: Sending {'event': {'event_type': 'state_changed', 'time_fired': datetime.datetime(2017, 3, 21, 17, 41, 13, 571784, tzinfo=<UTC>), 'origin': 'LOCAL', 'data': {'entity_id': 'cover.gordijnen_21', 'old_state': <state cover.gordijnen_21=open; Vera Device Id=21, current_position=100, supported_features=15, friendly_name=Gordijnen @ 2017-03-21T18:40:12.235209+01:00>, 'new_state': <state cover.gordijnen_21=open; Vera Device Id=21, current_position=51, supported_features=15, friendly_name=Gordijnen @ 2017-03-21T18:40:12.235209+01:00>}}, 'type': 'event', 'id': 2}
17-03-21 17:41:25 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 1823110032: Received {'service_data': {'entity_id': 'cover.gordijnen_21'}, 'service': 'close_cover', 'domain': 'cover', 'type': 'call_service', 'id': 11}
17-03-21 17:41:25 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 1823110032: Sending {'success': True, 'type': 'result', 'id': 11, 'result': None}
17-03-21 17:41:25 INFO (Vera Poll Thread) [pyvera.subscribe] Poll returned
```
The open command isn't logged by pyvera

**Comment by pavoni** [comment]
Thanks for the log - very helpful.

As I suspected your device isn't sending position updates for the open / close commands.

Should be a pretty easy fix.

Are you a developer (ie are you in a position to be able to test a branch if I put one together)?

**Comment by arjenfvellinga** [comment]
Yes I'm a developer, so happy to test your branch.

It would be the first time, so maybe you have some pointers when you are finished.
