### ISSUE TITLE
Support for scenes

### ISSUE THREAD

**Issue by Ardetus** [pavoni/pyvera#46]
Probably this is more like a feature request, but should there be support for scenes? I'm trying to get Nodon wall switches working with Home Assistant without success. I'm not sure if those switches should even work if there is no support for the scenes of Vera.

**Comment by pavoni** [comment]
From a brief look here (http://nodon.fr/support/NodOn_WallSwitch_ZWave_UserGuide_EN.pdf) it looks like they only function as scene controllers when connected to a gateway - so I think they would need some sort of scene integration to do anything.

From the description here (http://wiki.micasaverde.com/index.php/UI_Simple) we probably could monitor turning on and off scenes - and find a way to interact with them - possibly as switches in HA.

Will probably take a bit of reverse engineering - but the basic functions we need should already be there in `pyvera`.

Are you a developer - do you fancy a project?

**Comment by alanfischer** [comment]
I just ran into something similar.  I added some basic scene controller support in my fork here: https://github.com/alanfischer/pyvera

I'm not super satisfied with how I ended up implementing it, but it works great for me in HA (with a tiny patch for HA), and lets me use my minimote as a sensor to trigger automations.

**Comment by pavoni** [comment]
Looks like a great start @alanfischer - happy to help merge when you have something you're happy with.

**Comment by Ardetus** [comment]
I have done some development, but I really think you have now better idea how to solve this...Probably the modification what @alanfischer has already hacked, would solve the Nodon scene problem also. I would be also happy to test it, if you would merge the patches!

**Comment by alanfischer** [comment]
@Ardetus If you are interested to try it, here is a hass patch that goes along with the pending pyvera pull request for scenes.  It just adds the minimote as a sensor.


[hass_vera.txt](https://github.com/pavoni/pyvera/files/948414/hass_vera.txt)

**Comment by Ardetus** [comment]
Thank you for the patch! Unfortunately I don't see any difference with NodOn wallswitch... Probably scenes are not configured right on the Vera side.

**Comment by alanfischer** [comment]
If you wanted to get the contents of 2 urls from your vera, I could see if your NodOn switch is appearing slightly differently and if its something I could easily support.

http://YOUR_VERA_IP:3480/data_request?id=status
and
http://YOUR_VERA_IP:3480/data_request?id=sdata

**Comment by pavoni** [comment]
Closing since @alanfischer added scenes!
