### ISSUE TITLE
Add energy monitor sensor

### ISSUE THREAD

**Issue by pavoni** [pavoni/pyvera#47]
Useful data here https://pastebin.com/CwpvmtaL

Looks like the `device_category` is 'Power meter'

and useful attributes are 'kwh' and 'watts'

**Comment by pavoni** [comment]
@danodemano I'll probably make 'power' in W the main item to display - with `energy` in kwh as a secondary attribute. Does that make sense to you?

Something like this (excepy in W - kW makes sense for a while house - but probably not for a single device (unless you know better).
![screen shot 2017-04-12 at 10 57 41](https://cloud.githubusercontent.com/assets/4487313/24952344/0ae638fa-1f6f-11e7-8ae9-e6f71dc93e79.png)

**Comment by danodemano** [comment]
@pavoni - makes sense to me.  Watts is most likely the more important one but people will also want to see kwh as well, even for individual devices.  That can tell them how much a specific device is costing in electric.  

I know when the devices were tied straight to HA through zwave each of their values came across separately (watts, kwh, voltage, amps, etc).  Might just make sense to keep it the same.

**Comment by pavoni** [comment]
I did this the simple way for now (vera sensors are mapped to a single HA device).

Please test it if you can https://github.com/home-assistant/home-assistant/pull/7134
