### ISSUE TITLE
pyvera throwing exception error on dimmer state refresh

### ISSUE THREAD

**Issue by alanthewild** [pavoni/pyvera#54]
Not sure if this is only happening to me or to anyone else as well? 
Maybe not many people are using Vera and HomeAssistant?

Under the get_brightness def, line 577 of the __init__.py file, there is a reference to the **_level_** variable as an integer **_(int(level))_**. 

When refreshing the state of my dimmers from Vera, they return a % value (e.g. 20%) which causes an error in parsing the __init__py file as the 'level' variable is not an integer in that case but a string.

This generally happens every 2 or 3 days. Not sure why it occurs that infrequently.
I believe this has happened with all versions I've used so far - v0.39.x up to current v0.44.2 but I didn't notice earlier as I was always restarting Home Assistant while I was playing with it/setting things up. I've been using it for just over a month now.
I only really noticed this issue as I am graphing temperatures in grafana/InfluxDB and after this error, the temperature sensors in Vera stop updating in Home Assistant and therefore the graphs are blank.

I have implemented a workaround that forces the level variable to an integer if it is not already.
I am sure there are more elegant ways to get the same result?

I have added the following line to my local version today (line 577) above where the error normally occurs. This should strip the % character and change **_level_** to an integer if it is not already one.

**_level = int(level) if type(level) == int else float(level.strip('%'))_**

Full section (including extra line) is as follows (from line 565):

    def get_brightness(self, refresh=False):
        """Get dimmer brightness.

        Refresh data from Vera if refresh is True, otherwise use local cache.
        Refresh is only needed if you're not using subscriptions.
        Converts the Vera level property for dimmable lights from a percentage
        to the 0 - 255 scale used by HA.
        """
        if refresh:
            self.refresh()
        brightness = 0
        level = self.get_value('level')
        level = int(level) if type(level) == int else float(level.strip('%'))
        percent = 0 if level is None else int(level)
        if percent > 0:
            brightness = round(percent * 2.55)
        return int(brightness)

Will report back in 2 days if that hasn't resolved my issue.
If it does, can we get something similar added into the main branch?

Thanks,
Alan

**Comment by pavoni** [comment]
Thanks @alanthewild - very odd it goes wring so rarely - but the code is defensive - so not issue merging this.

HA will do their release next weekend - so let's fix during the week if it helps in your setup.

What Vera firmware are you using, and what hardware are the dimmers that cause the problem?

**Comment by pavoni** [comment]
I'm also using a couple of FGD-212s (I don't know what version) - although I haven't upgraded to the latest Vera Edge firmware.

I think we should add this - would you like to do a PR - or shall I just drop your change into the code?

**Comment by alanthewild** [comment]
Happy for you to drop my change into the code.
I just had to reboot my Synology so won't be another few days before I'm happy the fix is working properly.

So this issue wasn't affecting you? Just me? Weird. A firmware difference maybe?

Thinking back, I initially thought it was odd when some of my switch states were wrong - I'm running the latest version of AppDaemon with the new (beta) HA Dashboard and it's very obvious when that happens. I then looked into it further and after adding the DB for graphing temperatures figured out what was going wrong.

**Comment by alanthewild** [comment]
@pavoni Just noticed this other posting on HA with vera:
https://community.home-assistant.io/t/veraedge-issues-in-0-41/14032

It mentions a similar exception in HA if his vera dimmer was set to on but the brightness level was 0.0
Checked that behaviour in Python within my HA docker container.
Same issue, fixed by the code above. 

All good. He fixed his by not setting the level to 0.0 but I don't think that would fix it long term.
This will hopefully.

**Comment by alanthewild** [comment]
Thanks @pavoni 
Closing this issue as it's now resolved.
