### ISSUE TITLE
No virtual switch support?

### ISSUE THREAD

**Issue by maddox** [pavoni/pyvera#56]
I tried to add some virtual switches to my controller (`urn:schemas-upnp-org:device:VSwitch:1`) and they don't seem to show up in Home Assistant. Are these just not supported?

I'm trying to avoid polling when using the minimote, by using scenes native to Vera that set virtual switches on/off so that their state will push directly to Home Assistant and my automations will be instant.

**Comment by angoyd** [comment]
This should be rather easy to achieve. I will look into the code, to see if I can make a solution.

**Comment by angoyd** [comment]
I´ve been looking into this problem now and it looks like the VirtualSwitch that is created by the app https://apps.mios.com/plugin.php?id=1408 does not set correct category (=0 should be something like 3 (Onoff switch)) on the device in vera, that makes it to be filterd out by this component, but if you instead creates the virtual switch manually as the wiki describes http://wiki.micasaverde.com/index.php/Create_Virtual_Switch_Manually it gets the right category and is working as supposed, have tried it and it works as expected.

**Comment by pavoni** [comment]
So sounds like we do support this - as long as the device is set up correctly. Should I close the issue?

**Comment by pavoni** [comment]
Given the analysis above I'm going to close this. Please re-open if you don't think that's correct.
