### ISSUE TITLE
veraSecure and SMS messages?

### ISSUE THREAD

**Issue by MikeJohnshoy** [pavoni/pyvera#64]
I'm wondering if it might be worth getting the vera secure based on it having built-in wireless phone capability (it comes with a SIM card, or maybe I could provide my own?). The question is whether I could do anything with python to send an SMS message.  I haven't seen the vera secure software, so maybe this is built in and doesn't need to be done in python ...

**Comment by pavoni** [comment]
Afraid I don't know anything about vera secure. My vera can send alerts via SMS - but it does that via the internet connection I think.

Most of the vera calls are documented - so you may be able to do something if you feel like investigating.

Here is a place to start http://wiki.micasaverde.com/index.php/Luup_Requests#user_data

**Comment by pavoni** [comment]
Closing - not much we can do unless someone with a vera secure wants to contribute something.
