### ISSUE TITLE
pyvera does not properly handle non-english device categories

### ISSUE THREAD

**Issue by alanfischer** [pavoni/pyvera#70]
See the issue here: https://github.com/home-assistant/home-assistant/issues/9105

The device categories are of the form:
```
ContrÃ´leur de scÃ¨ne
MÃ©tÃ©o
DÃ©tecteur
DÃ©tecteur de tempÃ©rature
Appareil photo
Interrupteur On/Off
Panneau d'alarme
SirÃ¨ne
```

I wonder if there is some request parameter that would return the categories in English, otherwise it seems we would have to add translations in pyvera.  I havent found anything yet however...

**Comment by alanfischer** [comment]
Actually, reading through some vera docs, I saw this:

> Next are all the device categories listed in an array. Each category has a name and an id tag, like this: name="Thermostat" id="5". You will only see the categories for devices that exist in the MIOS installation. Always use the id for internal reference; the name changes based on the user's language.

So looks like we should use the id?  I'll look at some examples and verify that the id seems consistent across veras.  If so then I'll create a PR that uses the id instead of the name.

**Comment by r3dkross** [comment]
Thanks for helping, here is a part of the result of the request, if it can help:

http://192.168.1.15:3480/data_request?id=user_data&output_format=xml

```
<category_filter>
<category_filte id="1">
<categories/>
<Label lang_tag="ui7_all" text="Tout"/>
</category_filte>
<category_filte id="2">
<categories categorie="15"/>
<Label lang_tag="ui7_av_devices" text="Audio/Vido"/>
</category_filte>
<category_filte id="3">
<categories categorie="3"/>
<Label lang_tag="ui7_lights" text="Lumires"/>
</category_filte>
<category_filte id="4">
<categories categorie="6"/>
<Label lang_tag="ui7_cameras" text="Camras"/>
</category_filte>
<category_filte id="5">
<categories categorie="7"/>
<Label lang_tag="ui7_door_locks" text="Serrures lectroniques"/>
</category_filte>
<category_filte id="6">
<categories categorie="18"/>
<Label lang_tag="ui7_sensors" text="Dtecteurs"/>
</category_filte>
<category_filte id="7">
<categories categorie="5"/>
<Label lang_tag="ui7_thermostats" text="Thermostats"/>
</category_filte>
</category_filter>
```

Characters like é è à ô are showing wrong or there are emptied like the last request:

<Label lang_tag="ui7_av_devices" text="Audio/Vido"/>
"Audio/Vido" is **Audio/Vidéo**
<Label lang_tag="ui7_lights" text="Lumires"/>
Lumires is **Lumières**
<Label lang_tag="ui7_cameras" text="Camras"/>
Camras is **Caméras**
<Label lang_tag="ui7_door_locks" text="Serrures lectroniques"/>
Serrures lectroniques is **Serrures électroniques**
<Label lang_tag="ui7_sensors" text="Dtecteurs"/>
Dtecteurs is **Détecteurs**

and 

ContrÃ´leur de scÃ¨ne is : **Contrôleur de scène**
MÃ©tÃ©o is: **Météo**
DÃ©tecteur is: **Détecteur**
DÃ©tecteur de tempÃ©rature is: **Détecteur de température**
Appareil photo is correct
Interrupteur On/Off is correct
Panneau d'alarme is correct
SirÃ¨ne is: **Sirène**

Tell me if I can do something.

Thanks

**Comment by r3dkross** [comment]
I've not seen the second answer sorry.

I've checked the categories from the doc and mine:

**Categories founded from the doc:**
CATEGORY #2 - Dimmable Light **same for me**
CATEGORY #3 - Switch **same for me**
CATEGORY #4 - Security Sensor **same for me**
CATEGORY #5 - Thermostat **same for me**
CATEGORY #6 - Camera **same for me**
CATEGORY #7 - Door lock **same for me**
CATEGORY #8 - Window covering: **I don't own it**
CATEGORY #16 - Humidity sensor **I don't own it**
CATEGORY #17 - Temperature sensor **same for me**
CATEGORY #18 - Light sensor **same for me**
CATEGORY #21 - Power meter **I don't own it**

**Categories founded on mine:**

CATEGORY #14 - Keyboard
CATEGORY #15 - AV Devices
CATEGORY #24 - Siren
CATEGORY #25 - Weather

Look like id's are the same, should be a way to make it works :)

**Comment by pavoni** [comment]
Thanks for leaping on this @alanfischer - agree with what you suggest.

In case it helps - here is the extract from my vera.

We should get someone still on UI5 to check too. Some of the string descriptions were different (which is why we have some alternatives in the code) - hopefully the ids are the same...

````
<category_filter>
<category_filte id="1">
<categories/>
<Label lang_tag="ui7_all" text="All"/>
</category_filte>
<category_filte id="2">
<categories categorie="15"/>
<Label lang_tag="ui7_av_devices" text="Audio/Video"/>
</category_filte>
<category_filte id="3">
<categories categorie="3"/>
<Label lang_tag="ui7_lights" text="Lights"/>
</category_filte>
<category_filte id="4">
<categories categorie="6"/>
<Label lang_tag="ui7_cameras" text="Cameras"/>
</category_filte>
<category_filte id="5">
<categories categorie="7"/>
<Label lang_tag="ui7_door_locks" text="Door locks"/>
</category_filte>
<category_filte id="6">
<categories categorie="18"/>
<Label lang_tag="ui7_sensors" text="Sensors"/>
</category_filte>
<category_filte id="7">
<categories categorie="5"/>
<Label lang_tag="ui7_thermostats" text="Thermostats"/>
</category_filte>
</category_filter>
````

**Comment by alanfischer** [comment]
Ok, here is a branch that implements the category id check instead of category name.  It works for me.  However I only have switches, dimmers, and a thermostat.  So I dont know if its working for all the other device types.  I'd appreciate people trying it out.
https://github.com/alanfischer/pyvera/tree/use_ids

**Comment by r3dkross** [comment]
It doesn't seem to work for me:

```Python 3.5.4 (v3.5.4:3f56838976, Aug  7 2017, 12:56:33) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvera
>>> controller = pyvera.VeraController("http://192.168.1.15:3480/")
>>> devices = controller.get_devices('On/Off Switch')
>>> devices
[]
>>> ```

I've removed my old pyvera directory and replaced by the one on your repo.

**Comment by alanfischer** [comment]
What if you call get_devices with no parameters?  Just devices = controller.get_devices()

**Comment by r3dkross** [comment]
it works!
I've got them all!

```
>>> devices[2].is_switched_on()
False
>>> devices[2].switch_on()
>>> devices[2].is_switched_on()
True
>>> 
```

I've checked only the switch one's because I don't know what's the command to get temperature for example.

Nice one!!

**Comment by r3dkross** [comment]
Well It seems than I need your help another time, I have smoke sensors, they have 2 categories, the armedvariable is ok including the battery level and status but the second category including temperature is not recognized yet.

Here is one of them in home assistant:

binary_sensor.ddf_salon_205 | off | device_armed: True battery_level: 80 Vera Device Id: 205 friendly_name: DDF Salon



sensor.ddf_temp_salon_206 | Unknown | Vera Device Id: 206 friendly_name: DDF Temp Salon device_class: smoke

Any idea?

**Comment by alanfischer** [comment]
Ok, I think the issue is that the device category is still used in the vera integration for Home Assistant.  I'll modify my PR so that categories are nicely declared constants, and then make a corresponding Home Assistant PR that would switch to using those constants.  That should get us away from the english category names completely.  I'll update this thread when I have a branch of Home Assistant that works with the updated vera PR

**Comment by r3dkross** [comment]
Ok thanks!

**Comment by alanfischer** [comment]
You can try to use this pyvera branch: https://github.com/alanfischer/pyvera/tree/use_ids
And this hass branch: https://github.com/alanfischer/home-assistant/tree/pyvera_update
And see if things behave as expected.  I haven't tested it much yet however.

**Comment by r3dkross** [comment]
I'm a little bit lost about the bass branch, how I'm about to process? 
Uninstall the actual Hass installation?
Or is it another one to get installed next to the first one?
Thanks for help :)

**Comment by alanfischer** [comment]
To be safe, I would probably uninstall the previous hass installation (make sure you keep your configuration directory!), then clone & install the new hass from that branch I posted, and run that.  Make sure you are running the new pyvera from the branch too.  (If you install pyvera manually you can always run hass with --skip-pip to make sure it wont try to change any dependencies)

**Comment by pavoni** [comment]
@alanfischer Happy to release an interim version for testing if it makes life easier (that way your HA branch can just refer to the new version).

**Comment by alanfischer** [comment]
@r3dkross let me know if you are still having trouble testing this against a custom built hass and we can make it a bit easier.

**Comment by r3dkross** [comment]
Well I've cloned the whole branch on my computer, saved my config directory and uninstalled the old HA but im lost for running the cloned branched :/

**Comment by alanfischer** [comment]
You should be able to go into the cloned home-assistant directory, and just type:  `python setup.py install`

Once it finishes installing, type: `hass --skip-pip`

It should then still use the pyvera you built earlier.  But if you have problems with getting the pyvera dependency correct let us know.

**Comment by r3dkross** [comment]
Well I've got this issue:

```
Traceback (most recent call last):
  File "/usr/local/bin/hass", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'async-timeout==1.2.1' distribution was not found and is required by homeassistant
```

I've tried : 
pip install async-timeout

It's been installed but the issue is still here

**Comment by alanfischer** [comment]
@pavoni hmm, sounds like an interim release may help here

**Comment by pavoni** [comment]
@alanfischer Can you submit a PR - I'll then merge it and release an interim version.

**Comment by pavoni** [comment]
Should be available as 0.2.36a0 although I tried to call it 0.2.36alpha

**Comment by r3dkross** [comment]
I've downloaded it to my computer, ran the `python3 setup.py install ` in the folder, restarted HA with `hass --open-ui` and tada!! Sensors are corrects! 
I've tried with a 3 in 1 fiber motion sensor to check lux values and all is fine!
Better, when I turn on a switch from HA, the execution is faster than the vera...
So thanks for all the hard work guys!!

**Comment by alanfischer** [comment]
@r3dkross Excellent!
@pavoni I'll close this issue and we can discuss in the PR what changes are necessary before another release.  I was unsure about the Armed sensor stuff.

**Comment by pavoni** [comment]
Cool. 
On Armed sensors. Basically what the code is trying to do is create a switch as well as a sensor for each these devices. The switch arms or disarms the sensor. Armed sensors do things like send messages (via vera) when they trigger (when they are armed).

An example would be a movement detector used as an alarm. You arm it when you leave the house.

So we basically wrap the same vera object with 2 pyvera objects, and in HA you also get 2 devices with the same name.
