### ISSUE TITLE
Sensor values

### ISSUE THREAD

**Issue by dpembo** [pavoni/pyvera#73]
Looks like something which made it into todays release of HA causes significant problems with sensor values.  Had to back it out back to previous release.  Light sensors, temp, all showing 'unknown' in HA.

I did run it in debug for a few mins to see if anything was there but I lost the output :(

**Comment by dpembo** [comment]
these are multi-sensors that are armable and contain additional temp/light/etc sensors (e.g a fibaro and an aeotec one).  Guess is could've been the 'armable' changes

**Comment by pavoni** [comment]
Sorry for that - and thanks for backing out.

Will investigate, and fix.

**Comment by dpembo** [comment]
if you need me to test anything or assist with any debug, let me know, and I'll apply the pyvera files into my HA (or possibly setup a second instance so it doesn't annoy the family 👨‍👧‍👦 )

**Comment by alanfischer** [comment]
@dpembo Would you be able to post the contents of http://your_vera_url:3480/data_request?id=sdata

**Comment by dpembo** [comment]
attached is the xml output from the call - just slightly edited to remove some personal stuff
example ids of sensors I lost
129,130,131,132,133 (Aoetoc one)
81,82,83 (Fibaro one)

[output.txt](https://github.com/pavoni/pyvera/files/1335957/output.txt)

**Comment by alanfischer** [comment]
Would you mind sending me the json version?  That way I can load it right into pyvera and replicate your issue.

Thanks!

**Comment by jamesoft145** [comment]
Hera is a snippet of my JSON...

"devices": [ { "name": "6 in 1 Multisensor (humidity)", "altid": "m5", "id": 17, "category": 16, "subcategory": 0, "room": 2, "parent": 14, "humidity": "52" }, { "name": "6 in 1 Multisensor (light)", "altid": "m3", "id": 16, "category": 18, "subcategory": 0, "room": 2, "parent": 14, "light": "5" }, { "name": "6 in 1 Multisensor (temperature)", "altid": "m1", "id": 15, "category": 17, "subcategory": 0, "room": 2, "parent": 14, "temperature": "24.40" }, { "name": "6 in 1 Multisensor (uv)", "altid": "m27", "id": 18, "category": 28, "subcategory": 0, "room": 2, "parent": 14, "light": "0" },

**Comment by dpembo** [comment]
I'll sort an edited version of the full json response when I get back home later.

**Comment by dpembo** [comment]
[sample.json.txt](https://github.com/pavoni/pyvera/files/1344849/sample.json.txt)
attached my full (edited) json response also.

**Comment by alanfischer** [comment]
@dpembo @jamesoft145, Thanks for the help.  I see the problem.  It's related to the Home Assistant VeraSensor still using some of the old device category naming checking instead of id checking.  I'll get a fix into a branch and post it here if anyone wants to try it.

**Comment by dpembo** [comment]
excellent, thanks! More than happy to try it once posted :)

**Comment by alanfischer** [comment]
@dpembo The hass branch is here: https://github.com/alanfischer/home-assistant/tree/vera_sensor_fix

If this resolves your issues I'll make a PR for it.

**Comment by dpembo** [comment]
Good news for me... it works 👍 
![works](https://user-images.githubusercontent.com/9807493/31031457-84b22e70-a550-11e7-8b92-be80c62d5448.png)

**Comment by alanfischer** [comment]
Awesome, I'll close this issue & make the hass pr

**Comment by dpembo** [comment]
thank you :)

**Comment by tommkil** [comment]
Just installed a Fibaro fdgw-002 lotion and temperatur sensor wich Vera support in their latest firmware but it does not show up in Home assistent. Related to this?

**Comment by alanfischer** [comment]
I could take a look if you post the result of http://your_vera_url:3480/data_request?id=sdata

**Comment by tommkil** [comment]
Great, this is what i got

`{ "full": 1, "version": "*1.7.3830*", "model": "Sercomm NA301", "zwave_heal": 1, "temperature": "C", "skin": "mios", "serial_number": "45103638", "fwd1": "vera-eu-oem-relay12.mios.com", "fwd2": "vera-eu-oem-relay31.mios.com", "mode": 1, "sections": [ { "name": "My Home", "id": 1 } ], "rooms": [ { "name": "Garasje", "id": 6, "section": 1 }, { "name": "Hambrosvei", "id": 7, "section": 1 }, { "name": "KjÃ¸kken", "id": 9, "section": 1 }, { "name": "Sov nede", "id": 8, "section": 1 }, { "name": "Soverom master", "id": 10, "section": 1 }, { "name": "Spisestue", "id": 3, "section": 1 }, { "name": "Stue 1.etg", "id": 2, "section": 1 }, { "name": "Stue 2.etg", "id": 5, "section": 1 }, { "name": "Trapp", "id": 4, "section": 1 } ], "scenes": [ { "active": 0, "name": "Bryter H PÃ¥", "id": 13, "room": 0 }, { "active": 0, "name": "Bryter V PÃ¥", "id": 11, "room": 0 }, { "active": 1, "name": "Brytere Av", "id": 12, "room": 0 }, { "active": 1, "name": "Jul av", "id": 23, "room": 0 }, { "active": 0, "name": "Jul pÃ¥", "id": 22, "room": 0 }, { "active": 1, "name": "Lysbryter 2.etg Av", "id": 5, "room": 5 }, { "active": 0, "name": "Lysbryter 2.etg PÃ¥", "id": 4, "room": 5 }, { "active": 0, "name": "Nattlys", "id": 18, "room": 0 }, { "active": 1, "name": "Remote 1 Av", "id": 15, "room": 0 }, { "active": 0, "name": "Remote 1 PÃ¥", "id": 14, "room": 0 }, { "active": 1, "name": "Remote 2 Av", "id": 17, "room": 0 }, { "active": 0, "name": "Remote 2 PÃ¥", "id": 16, "room": 0 }, { "active": 1, "name": "Remote 3 Av", "id": 25, "room": 8 }, { "active": 0, "name": "Remote 3 pÃ¥", "id": 24, "room": 8 } ], "devices": [ { "name": "", "altid": "m4", "id": 303, "category": 21, "subcategory": 0, "room": 2, "parent": 302 }, { "name": "", "altid": "", "id": 309, "category": 0, "subcategory": -1, "room": 0, "parent": 0 }, { "name": "Alarm Av\/PÃ¥", "altid": "LS\/L2.0\/3E4174A\/01", "id": 138, "category": 3, "subcategory": 0, "room": 7, "parent": 10, "status": "0" }, { "name": "AvPa Kamera foran", "altid": "LS\/L2.0\/2D8688A\/01", "id": 43, "category": 3, "subcategory": 0, "room": 7, "parent": 10, "status": "1" }, { "name": "AvPÃ¥ Kamera bak", "altid": "LS\/L2.2\/0000010\/01", "id": 281, "category": 3, "subcategory": 0, "room": 7, "parent": 10, "status": "1" }, { "name": "Bevegelsesensor 2.et", "altid": "MS\/L2.0\/2CFB3F2\/16", "id": 79, "category": 4, "subcategory": 3, "room": 5, "parent": 10, "armed": "0", "armedtripped": "0", "lasttrip": "1526659973", "tripped": "1" }, { "name": "Bryter H", "altid": "LS\/L2.0\/00062C6\/01", "id": 121, "category": 3, "subcategory": 0, "room": 2, "parent": 10, "status": "1" }, { "name": "Bryter V", "altid": "LS\/L2.0\/00062C6\/02", "id": 112, "category": 3, "subcategory": 0, "room": 2, "parent": 10, "status": "0" }, { "name": "dataMine 2 graphing and logging plugin", "altid": "", "id": 259, "category": 0, "subcategory": -1, "room": 0, "parent": 0, "chcnt": "10" }, { "name": "Day or Night", "altid": "", "id": 90, "category": 0, "subcategory": -1, "room": 7, "parent": 0, "status": "1" }, { "name": "Garasje sensor", "altid": "8", "id": 356, "category": 4, "subcategory": 1, "room": 6, "parent": 1, "armed": "0", "lasttrip": "1526564181", "tripped": "1", "armedtripped": "1", "batterylevel": "100", "state": -1, "comment": "" }, { "name": "Garasje temperatur", "altid": "m1", "id": 357, "category": 17, "subcategory": 0, "room": 6, "parent": 356, "temperature": "22.80" }, { "name": "Garasjeport", "altid": "LS\/L2.0\/1F5D2B1\/02", "id": 83, "category": 3, "subcategory": 0, "room": 6, "parent": 10, "status": "0" }, { "name": "Garasjestatus 1", "altid": "DS\/L2.0\/11DA326\/10", "id": 76, "category": 4, "subcategory": 1, "room": 6, "parent": 10, "armed": "1", "armedtripped": "0", "lasttrip": "1526663287", "tripped": "0" }, { "name": "Glasslampe", "altid": "4", "id": 302, "category": 3, "subcategory": 0, "room": 2, "parent": 1, "status": "0", "watts": "0.0", "kwh": "4.4500", "commFailure": "0", "state": -1, "comment": "" }, { "name": "Julestjerne 1.etg", "altid": "LS\/L2.0\/1807270\/01", "id": 51, "category": 3, "subcategory": 0, "room": 3, "parent": 10, "status": "0" }, { "name": "Julestjerne 2.etg", "altid": "LS\/L2.0\/292D826\/01", "id": 61, "category": 3, "subcategory": 0, "room": 5, "parent": 10, "status": "0" }, { "name": "Juletre", "altid": "LS\/L2.0\/39B10CE\/01", "id": 46, "category": 3, "subcategory": 0, "room": 2, "parent": 10, "status": "0" }, { "name": "Kamera bak Av\/PÃ¥ 1", "altid": "RC\/L2.2\/0000010", "id": 282, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "KjÃ¸kkenlys", "altid": "LS\/L2.0\/0002715\/01", "id": 163, "category": 3, "subcategory": 0, "room": 9, "parent": 10, "status": "0" }, { "name": "Luftfuktighet ute", "altid": "HS\/TH2\/41985", "id": 177, "category": 16, "subcategory": 0, "room": 7, "parent": 10, "humidity": "95", "batterylevel": "100" }, { "name": "Lysbryter", "altid": "LS\/L2.0\/3856FF2\/16", "id": 142, "category": 3, "subcategory": 0, "room": 5, "parent": 10, "status": "0" }, { "name": "Ovnslys 2 etg", "altid": "5", "id": 331, "category": 2, "subcategory": 0, "room": 5, "parent": 1, "status": "0", "level": "0", "watts": "0.0", "kwh": "6.9200", "state": -1, "comment": "" }, { "name": "Ovnslys 2.etg 1", "altid": "RC\/L2.0\/00186FA", "id": 290, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "Regnsensor", "altid": "RS\/R2\/52736", "id": 180, "category": 12, "subcategory": -1, "room": 7, "parent": 10, "total_rain": "340.3", "rain_rate": "67.81", "batterylevel": "100" }, { "name": "Remote 1", "altid": "LS\/L2.0\/0893B2A\/01", "id": 124, "category": 3, "subcategory": 0, "room": 8, "parent": 10, "status": "0" }, { "name": "Remote 2", "altid": "LS\/L2.0\/0893B2A\/02", "id": 127, "category": 3, "subcategory": 0, "room": 8, "parent": 10, "status": "0" }, { "name": "Remote 3", "altid": "LS\/L2.0\/0893B2A\/03", "id": 128, "category": 3, "subcategory": 0, "room": 8, "parent": 10, "status": "1" }, { "name": "Remote jul 3", "altid": "LS\/L2.0\/075DB52\/03", "id": 234, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "1" }, { "name": "RFX Hum TH10\/18177", "altid": "HS\/TH10\/18177", "id": 244, "category": 16, "subcategory": 0, "room": 0, "parent": 10, "humidity": "48", "batterylevel": "100" }, { "name": "RFX Hum TH10\/41985", "altid": "HS\/TH10\/41985", "id": 322, "category": 16, "subcategory": 0, "room": 0, "parent": 10, "humidity": "47", "batterylevel": "100" }, { "name": "RFX Hum TH2\/14849", "altid": "HS\/TH2\/14849", "id": 308, "category": 16, "subcategory": 0, "room": 0, "parent": 10, "batterylevel": "100", "humidity": "38" }, { "name": "RFX Hum TH2\/26369", "altid": "HS\/TH2\/26369", "id": 306, "category": 16, "subcategory": 0, "room": 0, "parent": 10, "humidity": "96", "batterylevel": "100" }, { "name": "RFX Light L2.0\/075DB52\/01", "altid": "LS\/L2.0\/075DB52\/01", "id": 236, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "1" }, { "name": "RFX Light L2.0\/075DB52\/02", "altid": "LS\/L2.0\/075DB52\/02", "id": 237, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "1" }, { "name": "RFX Light L2.0\/1D0DBFA\/14", "altid": "LS\/L2.0\/1D0DBFA\/14", "id": 324, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L2.0\/1D0DBFA\/15", "altid": "LS\/L2.0\/1D0DBFA\/15", "id": 327, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L2.0\/1D0DBFA\/16", "altid": "LS\/L2.0\/1D0DBFA\/16", "id": 326, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "1" }, { "name": "RFX Light L2.0\/2CFB3F2\/15", "altid": "LS\/L2.0\/2CFB3F2\/15", "id": 245, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "1" }, { "name": "RFX Light L2.1\/0380380\/09", "altid": "LS\/L2.1\/0380380\/09", "id": 278, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/000000\/02", "altid": "LS\/L5.4\/000000\/02", "id": 247, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/000000\/14", "altid": "LS\/L5.4\/000000\/14", "id": 255, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "1" }, { "name": "RFX Light L5.4\/000001\/14", "altid": "LS\/L5.4\/000001\/14", "id": 256, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "1" }, { "name": "RFX Light L5.4\/000400\/02", "altid": "LS\/L5.4\/000400\/02", "id": 253, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/020000\/10", "altid": "LS\/L5.4\/020000\/10", "id": 251, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/030000\/10", "altid": "LS\/L5.4\/030000\/10", "id": 264, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/040000\/10", "altid": "LS\/L5.4\/040000\/10", "id": 276, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "1" }, { "name": "RFX Light L5.4\/040000\/14", "altid": "LS\/L5.4\/040000\/14", "id": 323, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/050000\/10", "altid": "LS\/L5.4\/050000\/10", "id": 297, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/080000\/14", "altid": "LS\/L5.4\/080000\/14", "id": 291, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/204000\/12", "altid": "LS\/L5.4\/204000\/12", "id": 293, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "1" }, { "name": "RFX Light L5.4\/208088\/02", "altid": "LS\/L5.4\/208088\/02", "id": 295, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/210080\/02", "altid": "LS\/L5.4\/210080\/02", "id": 274, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/21008C\/02", "altid": "LS\/L5.4\/21008C\/02", "id": 350, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/400001\/14", "altid": "LS\/L5.4\/400001\/14", "id": 249, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/404000\/12", "altid": "LS\/L5.4\/404000\/12", "id": 268, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/480010\/11", "altid": "LS\/L5.4\/480010\/11", "id": 270, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/800000\/11", "altid": "LS\/L5.4\/800000\/11", "id": 284, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/804000\/12", "altid": "LS\/L5.4\/804000\/12", "id": 272, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Light L5.4\/804404\/12", "altid": "LS\/L5.4\/804404\/12", "id": 328, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" }, { "name": "RFX Motion M\/FEF10C", "altid": "MS\/M\/FEF10C", "id": 140, "category": 4, "subcategory": 3, "room": 0, "parent": 10, "armed": "0", "armedtripped": "0" }, { "name": "RFX Rain R2\/11520", "altid": "RS\/R2\/11520", "id": 283, "category": 12, "subcategory": -1, "room": 0, "parent": 10, "total_rain": "293.8", "rain_rate": "0", "batterylevel": "100" }, { "name": "RFX Remote L2.0\/00062C6", "altid": "RC\/L2.0\/00062C6", "id": 238, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L2.0\/075DB52", "altid": "RC\/L2.0\/075DB52", "id": 235, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L2.0\/0893B2A", "altid": "RC\/L2.0\/0893B2A", "id": 241, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L2.0\/11DA326", "altid": "RC\/L2.0\/11DA326", "id": 240, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L2.0\/1D0DBFA", "altid": "RC\/L2.0\/1D0DBFA", "id": 325, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L2.0\/2CFB3F2", "altid": "RC\/L2.0\/2CFB3F2", "id": 239, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L2.0\/36A259E", "altid": "RC\/L2.0\/36A259E", "id": 260, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L2.0\/3856FF2", "altid": "RC\/L2.0\/3856FF2", "id": 242, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L2.1\/0380380", "altid": "RC\/L2.1\/0380380", "id": 279, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/000000", "altid": "RC\/L5.4\/000000", "id": 248, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/000001", "altid": "RC\/L5.4\/000001", "id": 257, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/000400", "altid": "RC\/L5.4\/000400", "id": 254, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/020000", "altid": "RC\/L5.4\/020000", "id": 252, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/030000", "altid": "RC\/L5.4\/030000", "id": 265, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/040000", "altid": "RC\/L5.4\/040000", "id": 277, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/050000", "altid": "RC\/L5.4\/050000", "id": 298, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/080000", "altid": "RC\/L5.4\/080000", "id": 292, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/204000", "altid": "RC\/L5.4\/204000", "id": 294, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/208088", "altid": "RC\/L5.4\/208088", "id": 296, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/210080", "altid": "RC\/L5.4\/210080", "id": 275, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/21008C", "altid": "RC\/L5.4\/21008C", "id": 351, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/400001", "altid": "RC\/L5.4\/400001", "id": 250, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/404000", "altid": "RC\/L5.4\/404000", "id": 269, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/480010", "altid": "RC\/L5.4\/480010", "id": 271, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/800000", "altid": "RC\/L5.4\/800000", "id": 285, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/804000", "altid": "RC\/L5.4\/804000", "id": 273, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Remote L5.4\/804404", "altid": "RC\/L5.4\/804404", "id": 329, "category": 666, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Temp T9\/41985", "altid": "TS\/T9\/41985", "id": 352, "category": 17, "subcategory": 0, "room": 0, "parent": 10 }, { "name": "RFX Temp TH10\/18177", "altid": "TS\/TH10\/18177", "id": 243, "category": 17, "subcategory": 0, "room": 0, "parent": 10, "temperature": "9.2", "batterylevel": "100" }, { "name": "RFX Temp TH10\/41985", "altid": "TS\/TH10\/41985", "id": 321, "category": 17, "subcategory": 0, "room": 0, "parent": 10, "temperature": "10.3", "batterylevel": "100" }, { "name": "RFX Temp TH2\/14849", "altid": "TS\/TH2\/14849", "id": 307, "category": 17, "subcategory": 0, "room": 0, "parent": 10, "batterylevel": "100", "temperature": "18.3" }, { "name": "RFX Temp TH2\/26369", "altid": "TS\/TH2\/26369", "id": 305, "category": 17, "subcategory": 0, "room": 0, "parent": 10, "temperature": "15.9", "batterylevel": "100" }, { "name": "RFX Wind W2\/31744", "altid": "WS\/W2\/31744", "id": 246, "category": 12, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Wind W2\/47872", "altid": "WS\/W2\/47872", "id": 266, "category": 12, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "RFX Wind W2\/50688", "altid": "WS\/W2\/50688", "id": 304, "category": 12, "subcategory": -1, "room": 0, "parent": 10, "direction": "180", "speed": "2", "gust": "2", "batterylevel": "100" }, { "name": "RFX Wind W2\/58368", "altid": "WS\/W2\/58368", "id": 330, "category": 12, "subcategory": -1, "room": 0, "parent": 10 }, { "name": "Rfxtrx", "altid": "", "id": 10, "category": 666, "subcategory": -1, "room": 0, "parent": 0, "commFailure": "0" }, { "name": "Soverom taklys", "altid": "3", "id": 299, "category": 2, "subcategory": 0, "room": 8, "parent": 1, "status": "0", "level": "0", "watts": "0.0", "kwh": "1.0800", "state": -1, "comment": "" }, { "name": "Spisestue taklys", "altid": "LS\/L2.0\/3F3450E\/01", "id": 29, "category": 3, "subcategory": 0, "room": 3, "parent": 10, "status": "0" }, { "name": "Spisestue_hovedlys", "altid": "7", "id": 347, "category": 2, "subcategory": 0, "room": 3, "parent": 1, "status": "0", "level": "0", "watts": "0.0", "kwh": "18.1000", "state": -1, "comment": "" }, { "name": "Steketermometer", "altid": "TS\/T2\/20226", "id": 141, "category": 17, "subcategory": 0, "room": 9, "parent": 10, "temperature": "21.3", "batterylevel": "100" }, { "name": "Stue lys Gostol", "altid": "LS\/L2.2\/0002711\/01", "id": 15, "category": 3, "subcategory": 0, "room": 2, "parent": 10, "status": "0" }, { "name": "Stue Lys sofa", "altid": "LS\/L2.0\/0002712\/01", "id": 17, "category": 3, "subcategory": 0, "room": 2, "parent": 10, "status": "0" }, { "name": "StÃ¥lampe", "altid": "LS\/L2.0\/29404BE\/01", "id": 65, "category": 3, "subcategory": 0, "room": 5, "parent": 10, "status": "0" }, { "name": "Temp Kjeller", "altid": "TS\/T2\/26625", "id": 169, "category": 17, "subcategory": 0, "room": 2, "parent": 10, "batterylevel": "100", "temperature": "10" }, { "name": "Temp ute", "altid": "TS\/TH2\/41985", "id": 176, "category": 17, "subcategory": 0, "room": 7, "parent": 10, "temperature": "-0.2", "batterylevel": "100" }, { "name": "Trapplys", "altid": "2", "id": 223, "category": 2, "subcategory": 0, "room": 4, "parent": 1, "status": "0", "level": "0", "watts": "0.0", "kwh": "188.5600", "commFailure": "0", "state": -1, "comment": "" }, { "name": "urn:schemas-upnp-org:device:ZonePlayer:1", "altid": "", "id": 354, "category": 0, "subcategory": -1, "room": 0, "parent": 0, "ip": "192.168.1.90" }, { "name": "urn:schemas-upnp-org:device:ZonePlayer:1 1", "altid": "", "id": 355, "category": 0, "subcategory": -1, "room": 0, "parent": 0, "ip": "192.168.1.137" }, { "name": "Utelys", "altid": "LS\/L2.0\/0002713\/01", "id": 161, "category": 3, "subcategory": 0, "room": 6, "parent": 10, "status": "0" }, { "name": "Vegglampe", "altid": "LS\/L2.0\/36A259E\/01", "id": 67, "category": 3, "subcategory": 0, "room": 5, "parent": 10, "status": "0" }, { "name": "Vind", "altid": "WS\/W2\/23552", "id": 178, "category": 12, "subcategory": -1, "room": 0, "parent": 10, "direction": "0", "speed": "0", "gust": "0", "batterylevel": "100" }, { "name": "Vind sensor", "altid": "WS\/W2\/50176", "id": 267, "category": 12, "subcategory": -1, "room": 7, "parent": 10, "batterylevel": "100", "direction": "45", "speed": "0", "gust": "2" }, { "name": "Z-Reserve 6", "altid": "LS\/L2.0\/2D47C4E\/01", "id": 49, "category": 3, "subcategory": 0, "room": 0, "parent": 10, "status": "0" } ], "categories": [ { "name": "Dimmable Switch", "id": 2 }, { "name": "On\/Off Switch", "id": 3 }, { "name": "Sensor", "id": 4 }, { "name": "Generic Sensor", "id": 12 }, { "name": "Humidity Sensor", "id": 16 }, { "name": "Temperature Sensor", "id": 17 }, { "name": "Power meter", "id": 21 } ], "ir": 0, "irtx": "", "loadtime": 1526626450, "dataversion": 626459508, "state": -1, "comment": "" }`

**Comment by tommkil** [comment]
Hi
Did you managed to look at this?

**Comment by thundergreen** [comment]
I have the same issue ... No temperature and lux showing in Hass but Vera ..here my Jason snippet:

'''
{ "full": 1, "version": "1.7.4001", "model": "Sercomm G450", "zwave_heal": 1, "temperature": "C", "skin": "mios", "serial_number": "50105158", "fwd1": "vera-us-oem-relay31.mios.com", "fwd2": "vera-us-oem-relay52.mios.com", "mode": 3, "sections": [ { "name": "My Home", "id": 1 } ], "rooms": [ { "name": "Living Room", "id": 2, "section": 1 }, { "name": "Rose", "id": 1, "section": 1 } ], "scenes": [ ], "devices": [ { "name": "LUX Livingroom", "altid": "m3", "id": 15, "category": 18, "subcategory": 0, "room": 2, "parent": 13, "light": "6" }, { "name": "LUX Rose", "altid": "m3", "id": 11, "category": 18, "subcategory": 0, "room": 1, "parent": 9, "light": "13" }, { "name": "Movement Livingroom", "altid": "4", "id": 13, "category": 4, "subcategory": 3, "room": 2, "parent": 1, "armed": "0", "armedtripped": "0", "lasttrip": "1538687494", "tripped": "0" }, { "name": "Movement Rose", "altid": "2", "id": 9, "category": 4, "subcategory": 3, "room": 1, "parent": 1, "armed": "0", "armedtripped": "0", "lasttrip": "1538687537", "tripped": "0", "state": -1, "comment": "" }, { "name": "Temp Livingroom", "altid": "m1", "id": 14, "category": 17, "subcategory": 0, "room": 2, "parent": 13, "temperature": "27.30" }, { "name": "Temp Rose", "altid": "m1", "id": 10, "category": 17, "subcategory": 0, "room": 1, "parent": 9, "temperature": "22.20" } ], "categories": [ { "name": "Sensor", "id": 4 }, { "name": "Temperature Sensor", "id": 17 }, { "name": "Light Sensor", "id": 18 } ], "ir": 0, "irtx": "", "loadtime": 1538687375, "dataversion": 687375107, "state": -1, "comment": "" }
'''

**Comment by pavoni** [comment]
@thundergreen This has been attached to an unrelated, closed issue. Could you open a new issue?

The categories looks fine - so you'll need to do some digging.

If you are a developer can you install the library, run python - replace the IP address below with your vera IP - and see what the following gives you.

```
>>> import pyvera

>>> controller = pyvera.VeraController("http://192.168.1.161:3480/")
>>> devices = controller.get_devices()
>>> devices
```
