### ISSUE TITLE
VeraDimmer.get_color() and VeraDimmer.set_color() don't seem to be working

### ISSUE THREAD

**Issue by josephlm** [pavoni/pyvera#96]
I am using PyVera CommitId: e2c527fd8042a2116a7f7a884c2536e854c4a2be (latest master at time of writing this).

I am using Vera Hub Plus with F/W: 1.7.3831 (latest F/W at time of writing this)
I had originally tried with F/W "1.7.3307". Both Firmware versions fail to let me get/set color.

I am using Philips Hue Light as example. I am able to get/set colors from the Vera app (3.17) on an IPhone.

I am able to get/set brightness and power.

I am willing to help resolve this if you know where to start looking. I used the example app "device_listener.py" to track color changes I made in the iphone Vera app and it did not show anything related to color in the payload. The payload from device_listener looked as follows and didn't change in value between color changes, but it does re-print the same payload when color changes:

"
Living Room_10: {u'category': 2, u'status': u'1', u'room': u'1', u'parent': u'6', u'altid': u'hueLamp_4', u'level': u'100', u'commFailure': u'0', u'name': u'Living Room', 'categoryName': u'Dimmable Switch', u'id': u'10', u'subcategory': u'-1'}
"

**Comment by alanfischer** [comment]
I'm not sure off hand what might be wrong, but for starters if you could report what you get for: 
http://your_vera_url:3480/data_request?id=sdata
Then I could start looking into it.

**Comment by josephlm** [comment]
Hi Alan,

Thanks for responding.

Here is the payload you’ve requested:


{ "full": 1, "version": "*1.7.3831*", "model": "Sercomm G450", "zwave_heal": 1, "temperature": "F", "skin": "mios", "serial_number": "50016225", "fwd1": "vera-us-oem-relay41.mios.com<http://vera-us-oem-relay41.mios.com>", "fwd2": "vera-us-oem-relay62.mios.com<http://vera-us-oem-relay62.mios.com>", "mode": 1, "sections": [ { "name": "My Home", "id": 1 } ], "rooms": [ ], "scenes": [ ], "devices": [ { "name": "HueLamp 1: Hue color lamp 1", "altid": "hueLamp_1", "id": 7, "category": 2, "subcategory": -1, "room": 0, "parent": 6, "status": "0", "level": "0", "commFailure": "1" }, { "name": "HueLamp 2: Hue color lamp 2", "altid": "hueLamp_2", "id": 8, "category": 2, "subcategory": -1, "room": 0, "parent": 6, "status": "0", "level": "0", "commFailure": "1" }, { "name": "HueLamp 3: Hue color lamp 3", "altid": "hueLamp_3", "id": 9, "category": 2, "subcategory": -1, "room": 0, "parent": 6, "status": "0", "level": "0", "commFailure": "1" }, { "name": "Living Room", "altid": "hueLamp_4", "id": 10, "category": 2, "subcategory": -1, "room": 0, "parent": 6, "status": "1", "level": "100", "commFailure": "0" }, { "name": "Philips Hue Plugin", "altid": "", "id": 6, "category": 26, "subcategory": -1, "room": 0, "parent": 0, "ip": "192.168.2.199", "commFailure": "0", "state": -1, "comment": "" } ], "categories": [ { "name": "Dimmable Switch", "id": 2 }, { "name": "Philips Controller", "id": 26 } ], "ir": 0, "irtx": "", "loadtime": 1531327245, "dataversion": 327245092, "state": -1, "comment": "" }

Thanks,

Joey Morrow

On Jul 11, 2018, at 8:39 AM, Alan Fischer <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure off hand what might be wrong, but for starters if you could report what you get for:
http://your_vera_url:3480/data_request?id=sdata
Then I could start looking into it.

**Comment by josephlm** [comment]
Here it is passed through pretty print:

{
  "full": 1,
  "version": "*1.7.3831*",
  "model": "Sercomm G450",
  "zwave_heal": 1,
  "temperature": "F",
  "skin": "mios",
  "serial_number": "50016225",
  "fwd1": "vera-us-oem-relay41.mios.com<http:\/\/vera-us-oem-relay41.mios.com>",
  "fwd2": "vera-us-oem-relay62.mios.com<http:\/\/vera-us-oem-relay62.mios.com>",
  "mode": 1,
  "sections": [
    {
      "name": "My Home",
      "id": 1
    }
  ],
  "rooms": [
    
  ],
  "scenes": [
    
  ],
  "devices": [
    {
      "name": "HueLamp 1: Hue color lamp 1",
      "altid": "hueLamp_1",
      "id": 7,
      "category": 2,
      "subcategory": -1,
      "room": 0,
      "parent": 6,
      "status": "0",
      "level": "0",
      "commFailure": "1"
    },
    {
      "name": "HueLamp 2: Hue color lamp 2",
      "altid": "hueLamp_2",
      "id": 8,
      "category": 2,
      "subcategory": -1,
      "room": 0,
      "parent": 6,
      "status": "0",
      "level": "0",
      "commFailure": "1"
    },
    {
      "name": "HueLamp 3: Hue color lamp 3",
      "altid": "hueLamp_3",
      "id": 9,
      "category": 2,
      "subcategory": -1,
      "room": 0,
      "parent": 6,
      "status": "0",
      "level": "0",
      "commFailure": "1"
    },
    {
      "name": "Living Room",
      "altid": "hueLamp_4",
      "id": 10,
      "category": 2,
      "subcategory": -1,
      "room": 0,
      "parent": 6,
      "status": "1",
      "level": "100",
      "commFailure": "0"
    },
    {
      "name": "Philips Hue Plugin",
      "altid": "",
      "id": 6,
      "category": 26,
      "subcategory": -1,
      "room": 0,
      "parent": 0,
      "ip": "192.168.2.199",
      "commFailure": "0",
      "state": -1,
      "comment": ""
    }
  ],
  "categories": [
    {
      "name": "Dimmable Switch",
      "id": 2
    },
    {
      "name": "Philips Controller",
      "id": 26
    }
  ],
  "ir": 0,
  "irtx": "",
  "loadtime": 1531327245,
  "dataversion": 327245092,
  "state": -1,
  "comment": ""
}

Also, I should mention I'm only testing with light bulb 4. The hue bridge came with all 4 bulbs preconfigured. The other three bulbs I've never turned on.

**Comment by alanfischer** [comment]
Thanks, if you could also paste the result of
http://your_vera_url:3480/data_request?id=status
then I should have everything

**Comment by josephlm** [comment]
Pretty Printed:

{
  "startup": {
    "tasks": [
      
    ]
  },
  "devices": [
    {
      "id": 1,
      "states": [
        {
          "id": 389,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "Use45",
          "value": "1"
        },
        {
          "id": 390,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "UseMR",
          "value": "0"
        },
        {
          "id": 391,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "LimitNeighbors",
          "value": "0"
        },
        {
          "id": 392,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "LastUpdate",
          "value": "1531346004"
        },
        {
          "id": 393,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "NetStatusID",
          "value": "1"
        },
        {
          "id": 394,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "NetStatusText",
          "value": "OK"
        },
        {
          "id": 395,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "LockComPort",
          "value": "1"
        },
        {
          "id": 396,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "ComPort",
          "value": "\/dev\/ttyS0"
        },
        {
          "id": 397,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "PollingEnabled",
          "value": "1"
        },
        {
          "id": 398,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "PollDelayInitial",
          "value": "20"
        },
        {
          "id": 399,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "PollDelayDeadTime",
          "value": "10"
        },
        {
          "id": 400,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "PollMinDelay",
          "value": "30"
        },
        {
          "id": 401,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "PollFrequency",
          "value": "60"
        },
        {
          "id": 402,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "VersionInfo",
          "value": "6.1 L:1"
        },
        {
          "id": 403,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "HomeID",
          "value": "House: 80dd4099 Node 1 Suc 0"
        },
        {
          "id": 404,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "Role",
          "value": "Master SIS:NO PRI:YES"
        },
        {
          "id": 405,
          "service": "urn:micasaverde-com:serviceId:ZWaveNetwork1",
          "variable": "LastDongleBackup",
          "value": ""
        },
        {
          "id": 406,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "AutoConfigure",
          "value": "1"
        },
        {
          "id": 407,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailure",
          "value": "0"
        },
        {
          "id": 408,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailureTime",
          "value": "0"
        },
        {
          "id": 409,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailureAlarm",
          "value": "1528217286,0"
        },
        {
          "id": 410,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "LastTimeOffset",
          "value": "-7"
        },
        {
          "id": 411,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "Configured",
          "value": "0"
        }
      ],
      "Jobs": [
        
      ],
      "PendingJobs": 0,
      "tooltip": {
        "display": 0
      },
      "status": -1
    },
    {
      "id": 2,
      "states": [
        {
          "id": 185,
          "service": "urn:micasaverde-com:serviceId:BluetoothNetwork1",
          "variable": "NetStatusID",
          "value": "0"
        },
        {
          "id": 186,
          "service": "urn:micasaverde-com:serviceId:BluetoothNetwork1",
          "variable": "NetStatusText",
          "value": "OK"
        },
        {
          "id": 187,
          "service": "urn:micasaverde-com:serviceId:BluetoothNetwork1",
          "variable": "BLEAddress",
          "value": "D4:60:E3:FB:09:14"
        },
        {
          "id": 188,
          "service": "urn:micasaverde-com:serviceId:BluetoothNetwork1",
          "variable": "BLEScanTimeout",
          "value": "10"
        },
        {
          "id": 189,
          "service": "urn:micasaverde-com:serviceId:BluetoothNetwork1",
          "variable": "PollingEnabled",
          "value": "1"
        },
        {
          "id": 190,
          "service": "urn:micasaverde-com:serviceId:BluetoothNetwork1",
          "variable": "PollDelayInitial",
          "value": "20"
        },
        {
          "id": 191,
          "service": "urn:micasaverde-com:serviceId:BluetoothNetwork1",
          "variable": "PollMinDelay",
          "value": "60"
        },
        {
          "id": 192,
          "service": "urn:micasaverde-com:serviceId:BluetoothNetwork1",
          "variable": "PollFrequency",
          "value": "60"
        },
        {
          "id": 193,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailure",
          "value": "1"
        },
        {
          "id": 194,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailureTime",
          "value": "1528217293"
        },
        {
          "id": 195,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "Configured",
          "value": "0"
        }
      ],
      "Jobs": [
        
      ],
      "PendingJobs": 0,
      "tooltip": {
        "display": 1,
        "tag2": "Can't Detect Device"
      },
      "status": 2
    },
    {
      "id": 3,
      "states": [
        {
          "id": 321,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "LockComPort",
          "value": "1"
        },
        {
          "id": 322,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "ComPort",
          "value": "\/dev\/ttyS2"
        },
        {
          "id": 323,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "NetStatusID",
          "value": "0"
        },
        {
          "id": 324,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "NetStatusText",
          "value": "OK"
        },
        {
          "id": 325,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "RediscoverEnabled",
          "value": "1"
        },
        {
          "id": 326,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "RediscoverInitialDelay",
          "value": "60"
        },
        {
          "id": 327,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "RediscoverMinDelay",
          "value": "120"
        },
        {
          "id": 328,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "RediscoverFreq",
          "value": "120"
        },
        {
          "id": 329,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "PollingEnabled",
          "value": "1"
        },
        {
          "id": 330,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "PollDelayInitial",
          "value": "20"
        },
        {
          "id": 331,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "PollMinDelay",
          "value": "60"
        },
        {
          "id": 332,
          "service": "urn:micasaverde-com:serviceId:ZigbeeNetwork1",
          "variable": "PollFrequency",
          "value": "60"
        },
        {
          "id": 333,
          "service": "urn:micasaverde-com:serviceId:ZigbeeDevice1",
          "variable": "StackVersion",
          "value": "5.6.0 GA build 231"
        },
        {
          "id": 334,
          "service": "urn:micasaverde-com:serviceId:ZigbeeDevice1",
          "variable": "ZigbeePanID",
          "value": "b760"
        },
        {
          "id": 335,
          "service": "urn:micasaverde-com:serviceId:ZigbeeDevice1",
          "variable": "ZigbeeEPanID",
          "value": "24165622d9f6ec2c"
        },
        {
          "id": 336,
          "service": "urn:micasaverde-com:serviceId:ZigbeeDevice1",
          "variable": "ZigbeeChannel",
          "value": "11"
        },
        {
          "id": 337,
          "service": "urn:micasaverde-com:serviceId:ZigbeeDevice1",
          "variable": "PendingRemoveDevices",
          "value": ""
        },
        {
          "id": 338,
          "service": "urn:micasaverde-com:serviceId:ZigbeeDevice1",
          "variable": "UnknownDevices",
          "value": ""
        },
        {
          "id": 339,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "Configured",
          "value": "0"
        }
      ],
      "Jobs": [
        
      ],
      "PendingJobs": 0,
      "tooltip": {
        "display": 0
      },
      "status": -1
    },
    {
      "id": 4,
      "states": [
        {
          "id": 49,
          "service": "urn:micasaverde-com:serviceId:SceneController1",
          "variable": "Scenes",
          "value": ""
        },
        {
          "id": 50,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "IgnoreRoom",
          "value": "1"
        },
        {
          "id": 51,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "Configured",
          "value": "0"
        }
      ],
      "Jobs": [
        
      ],
      "PendingJobs": 0,
      "tooltip": {
        "display": 0
      },
      "status": -1
    },
    {
      "id": 6,
      "states": [
        {
          "id": 339,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "Bridges",
          "value": ""
        },
        {
          "id": 340,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "Status",
          "value": "Philips Hue Connected!"
        },
        {
          "id": 341,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "DebugMode",
          "value": "0"
        },
        {
          "id": 342,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "POLLING_RATE",
          "value": "10"
        },
        {
          "id": 343,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "FailedStatusReport",
          "value": "0"
        },
        {
          "id": 344,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BridgeLink",
          "value": "1"
        },
        {
          "id": 345,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BridgeId",
          "value": "001788FFFE612AA6"
        },
        {
          "id": 346,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "First_Run",
          "value": "TRUE"
        },
        {
          "id": 347,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BridgeScenes",
          "value": "{ \"nKc24CfvVwml6Ac\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Dimmed\" }, \"TVe0ycV1XyhanU-\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Arctic aurora\" }, \"7XyOe4daefLrJvS\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Savanna sunset\" }, \"5utNjHMBfvCbALR\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Read\" }, \"LrF2WUCdMC86uOL\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Spring blossom\" }, \"JpcWR2yNsKpShMU\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Concentrate\" }, \"kWSm5PWSTHXfCM1\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Energize\" }, \"Dqx6WUsEB-hoQGu\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Relax\" }, \"EWqEJg9hajxiS7i\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Bright\" }, \"XPtkUuNorHBLWpb\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Nightlight\" }, \"hkaVTU8-hy4NLx2\": { \"lights\": [ \"4\" ], \"version\": 2, \"name\": \"Tropical twilight\" } }"
        },
        {
          "id": 348,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BridgeFWVersion",
          "value": "1.24.0"
        },
        {
          "id": 349,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BridgeModel",
          "value": "BSB002"
        },
        {
          "id": 350,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BridgeFavoriteScenes",
          "value": "nKc24CfvVwml6Ac,TVe0ycV1XyhanU-,7XyOe4daefLrJvS,5utNjHMBfvCbALR,LrF2WUCdMC86uOL,JpcWR2yNsKpShMU"
        },
        {
          "id": 351,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "FirstRun",
          "value": "0"
        },
        {
          "id": 352,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "ActionListScenes",
          "value": "nKc24CfvVwml6Ac;Dimmed;TVe0ycV1XyhanU-;Arctic aurora;7XyOe4daefLrJvS;Savanna sunset;5utNjHMBfvCbALR;Read;LrF2WUCdMC86uOL;Spring blossom;JpcWR2yNsKpShMU;Concentrate;kWSm5PWSTHXfCM1;Energize;Dqx6WUsEB-hoQGu;Relax;EWqEJg9hajxiS7i;Bright;XPtkUuNorHBLWpb;Nightlight;hkaVTU8-hy4NLx2;Tropical twilight;"
        },
        {
          "id": 353,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "HuePresetTriggers",
          "value": "nKc24CfvVwml6Ac,Dimmed;TVe0ycV1XyhanU-,Arctic aurora;7XyOe4daefLrJvS,Savanna sunset;5utNjHMBfvCbALR,Read;LrF2WUCdMC86uOL,Spring blossom;JpcWR2yNsKpShMU,Concentrate;kWSm5PWSTHXfCM1,Energize;Dqx6WUsEB-hoQGu,Relax;EWqEJg9hajxiS7i,Bright;XPtkUuNorHBLWpb,Nightlight;hkaVTU8-hy4NLx2,Tropical twilight;"
        },
        {
          "id": 354,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BridgeLights",
          "value": "1,Hue color lamp 1;2,Hue color lamp 2;3,Hue color lamp 3;4,Living Room 4 HueName"
        },
        {
          "id": 355,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "StateForAll",
          "value": "1"
        },
        {
          "id": 356,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailure",
          "value": "0"
        },
        {
          "id": 357,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailureTime",
          "value": "0"
        },
        {
          "id": 358,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "Configured",
          "value": "0"
        }
      ],
      "Jobs": [
        
      ],
      "PendingJobs": 0,
      "tooltip": {
        "display": 0
      },
      "status": -1
    },
    {
      "id": 8,
      "states": [
        {
          "id": 219,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BulbModelID",
          "value": "LCT016"
        },
        {
          "id": 220,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "IconValue",
          "value": "R"
        },
        {
          "id": 221,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampValues",
          "value": "hue:0;sat:0"
        },
        {
          "id": 222,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampHexValue",
          "value": "#FFFFFF"
        },
        {
          "id": 223,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampEffectValue",
          "value": "none"
        },
        {
          "id": 224,
          "service": "urn:upnp-org:serviceId:SwitchPower1",
          "variable": "Status",
          "value": "0"
        },
        {
          "id": 225,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "TurnOnBeforeDim",
          "value": "0"
        },
        {
          "id": 226,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "LoadLevelStatus",
          "value": "0"
        },
        {
          "id": 227,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "LoadLevelTarget",
          "value": "0"
        },
        {
          "id": 228,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "ModeSetting",
          "value": "1:;2:;3:;4:"
        },
        {
          "id": 229,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailure",
          "value": "1"
        },
        {
          "id": 230,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailureTime",
          "value": "1528504032"
        },
        {
          "id": 231,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "Configured",
          "value": "0"
        }
      ],
      "Jobs": [
        
      ],
      "PendingJobs": 0,
      "tooltip": {
        "display": 1,
        "tag2": "Can't Detect Device"
      },
      "status": 2
    },
    {
      "id": 10,
      "states": [
        {
          "id": 289,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BulbModelID",
          "value": "LCT016"
        },
        {
          "id": 290,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "IconValue",
          "value": "ABY"
        },
        {
          "id": 291,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampValues",
          "value": "ct:366"
        },
        {
          "id": 292,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampHexValue",
          "value": "#FFCCA3"
        },
        {
          "id": 293,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampEffectValue",
          "value": "none"
        },
        {
          "id": 294,
          "service": "urn:upnp-org:serviceId:SwitchPower1",
          "variable": "Status",
          "value": "1"
        },
        {
          "id": 295,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "TurnOnBeforeDim",
          "value": "0"
        },
        {
          "id": 296,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "LoadLevelLast",
          "value": "1"
        },
        {
          "id": 297,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "LoadLevelStatus",
          "value": "1"
        },
        {
          "id": 298,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "LoadLevelTarget",
          "value": "1"
        },
        {
          "id": 299,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "ModeSetting",
          "value": "1:;2:;3:;4:"
        },
        {
          "id": 300,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailure",
          "value": "0"
        },
        {
          "id": 301,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailureTime",
          "value": "0"
        },
        {
          "id": 302,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "TransitionTime",
          "value": "50"
        },
        {
          "id": 303,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailureAlarm",
          "value": "1531248517,0"
        },
        {
          "id": 304,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "Configured",
          "value": "0"
        }
      ],
      "Jobs": [
        
      ],
      "PendingJobs": 0,
      "tooltip": {
        "display": 0
      },
      "status": -1
    },
    {
      "id": 11,
      "states": [
        {
          "id": 219,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BulbModelID",
          "value": "LCT016"
        },
        {
          "id": 220,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "IconValue",
          "value": "R"
        },
        {
          "id": 221,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampValues",
          "value": "hue:0;sat:0"
        },
        {
          "id": 222,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampHexValue",
          "value": "#FFFFFF"
        },
        {
          "id": 223,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampEffectValue",
          "value": "none"
        },
        {
          "id": 224,
          "service": "urn:upnp-org:serviceId:SwitchPower1",
          "variable": "Status",
          "value": "0"
        },
        {
          "id": 225,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "TurnOnBeforeDim",
          "value": "0"
        },
        {
          "id": 226,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "LoadLevelStatus",
          "value": "0"
        },
        {
          "id": 227,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "LoadLevelTarget",
          "value": "0"
        },
        {
          "id": 228,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "Configured",
          "value": "0"
        },
        {
          "id": 229,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "ModeSetting",
          "value": "1:;2:;3:;4:"
        },
        {
          "id": 230,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailure",
          "value": "1"
        },
        {
          "id": 231,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailureTime",
          "value": "1531346013"
        }
      ],
      "Jobs": [
        
      ],
      "PendingJobs": 0,
      "tooltip": {
        "display": 1,
        "tag2": "Can't Detect Device"
      },
      "status": 2
    },
    {
      "id": 12,
      "states": [
        {
          "id": 219,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "BulbModelID",
          "value": "LCT016"
        },
        {
          "id": 220,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "IconValue",
          "value": "R"
        },
        {
          "id": 221,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampValues",
          "value": "hue:0;sat:0"
        },
        {
          "id": 222,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampHexValue",
          "value": "#FFFFFF"
        },
        {
          "id": 223,
          "service": "urn:micasaverde-com:serviceId:PhilipsHue1",
          "variable": "LampEffectValue",
          "value": "none"
        },
        {
          "id": 224,
          "service": "urn:upnp-org:serviceId:SwitchPower1",
          "variable": "Status",
          "value": "0"
        },
        {
          "id": 225,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "TurnOnBeforeDim",
          "value": "0"
        },
        {
          "id": 226,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "LoadLevelStatus",
          "value": "0"
        },
        {
          "id": 227,
          "service": "urn:upnp-org:serviceId:Dimming1",
          "variable": "LoadLevelTarget",
          "value": "0"
        },
        {
          "id": 228,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "Configured",
          "value": "0"
        },
        {
          "id": 229,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "ModeSetting",
          "value": "1:;2:;3:;4:"
        },
        {
          "id": 230,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailure",
          "value": "1"
        },
        {
          "id": 231,
          "service": "urn:micasaverde-com:serviceId:HaDevice1",
          "variable": "CommFailureTime",
          "value": "1531346013"
        }
      ],
      "Jobs": [
        
      ],
      "PendingJobs": 0,
      "tooltip": {
        "display": 1,
        "tag2": "Can't Detect Device"
      },
      "status": 2
    }
  ],
  "Using_2G": 0,
  "LoadTime": 1531346052,
  "DataVersion": 346003154,
  "UserData_DataVersion": 346003006,
  "TimeStamp": 1531348012,
  "lights_on": 1,
  "lights_off": 3,
  "doors_locked": 0,
  "doors_unlocked": 0,
  "sensors_tripped": 0,
  "sensors_not_tripped": 0,
  "failed_devices": 3,
  "visible_devices": 5,
  "partitions_active": 0,
  "partitions_notactive": 0,
  "ZWaveStatus": 1,
  "Mode": 1,
  "LocalTime": "2018-07-11 15:26:52 N"
}

**Comment by alanfischer** [comment]
Thanks.  It looks like the Hue bulbs have their own PhillipsHue service instead of the standard vera color service.  That would explain why they don't work with the set/get color methods.  The change to also support Hue wouldn't be too difficult to implement if you are somewhat comfortable in python.

**Comment by toggledbits** [comment]
There's an update Hue plugin (AltHue) for Vera that fixes a lot of the ills of Vera's own plugin. I recommend trying it if you're on Vera's (old) plugin, and see if that addresses your issue. If not, I'm sure the plugin developer (amg0) would be willing to address it. It does not seem to me that coding an exception in pyvera is the right approach.

ref: http://forum.micasaverde.com/index.php/topic,77266.msg373381.html#msg373381

**Comment by pavoni** [comment]
Closing the issue given the discussion above.
